services:
  milesbot:
    image: milesbot:latest
    env_file:
      - .env
    volumes:
      - milesbot_data:/app/database

  ffmpeg:
    image: lscr.io/linuxserver/ffmpeg:latest

volumes:
  milesbot_data:
