export const CONFIRM_DELETE_CAMPAIGN = "confirm_delete_campaign_";
export const CANCEL_BUTTON_ID = "cancel_button";

export const TEST_ENV_WARNING =
  "⚠️ MAINTENANCE MODE: This data is from a test database and is not accurate";

export const ERROR_COLOR = 0xd80032;
export const SUCCESS_COLOR = 0x23ce6b;
export const CELESTIAL_BLUE = 0x39a0ed;

export const DM_ROLE_NAME = "DM";

export const VIEW_CAMPAIGN_BUTTON_ID_PREFIX = "`manage_campaigns_";

export const VALID_UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export const MILES_RANDOM_RESPONSES: string[] = [
  "You forgot me again!",
  "Seriously, how many times do I have to remind you?",
  "I'm still here, you know!",
  "Don't leave me hanging this time.",
  "Come on, remember me now!",
  "I thought you had my back!",
  "Left me behind again? Not cool.",
  "Hey, where's Miles?",
  "Guess I'm still the forgotten one.",
  "You didn't forget me... did you?",
  "Still waiting here...",
  "Next time, include me!",
  "Miles is right here!",
  "Don't leave me out of the adventure!",
  "I was just left behind!",
  "Are you going to remember me this time?",
  "No more leaving me behind, okay?",
  "Come back for me!",
  "Don't leave Miles stranded!",
  "It's not miles call me the baron.",
  "I used to be respected and feared!",
  "Why do you keep forgetting me?",
  "I know I'm here, just not in your plans.",
  "You can't keep leaving me behind like this.",
  "Miles is waiting patiently.",
  "Don't make me wait again.",
  "I deserve to be part of the journey.",
  "Don't overlook me this time.",
  "Miles isn't going anywhere!",
  "Remember, I need you too.",
  "Don't ignore me like before.",
  "I'm not just background, you know.",
  "Miles here, still part of the team.",
  "You can't just leave me behind.",
  "I'm still eager to help!",
  "Don't forget about Miles in the heat of battle.",
  "I'm counting on you to remember me.",
  "Miles is here, don't leave me out.",
  "Let me join the next quest!",
  "Don't leave your faithful companion behind.",
  "I'm ready whenever you are.",
  "Miles won't wait forever.",
  "Don't keep leaving me in the shadows.",
  "Remember our promise, don't abandon me.",
  "Miles here, still standing.",
  "I won't be forgotten this time.",
  "Stay with me, let's go together.",
  "Don't make Miles stay behind again.",
  "I'm still needed, don't leave me out.",
  "Miles is by your side, don't stray.",
  "I feel left out, include me!",
  "Don't make me feel abandoned.",
  "Miles is here to support you.",
  "I won't let you forget me.",
  "Don't dismiss Miles like before.",
  "I'm part of the team, remember?",
  "Don't leave me in the wilderness.",
  "Miles is ready for the next challenge.",
  "Don't make me wander alone.",
  "I need you as much as you need me.",
  "Miles won't leave without you.",
  "Don't leave me behind in the dark.",
  "I'm still here to help.",
  "Don't forget, Miles has your back.",
  "I'm waiting here, don't ignore me.",
  "Miles is here, always ready.",
  "Don't let me be left behind again.",
  "I'm counting on you to remember me.",
  "Don't leave me stranded.",
  "Miles wants to be part of the story.",
  "I'm not just a name, I'm here.",
  "Don't abandon your friend Miles.",
  "Miles is part of the adventure.",
  "Don't leave me hanging.",
  "I'm still here to help.",
  "Miles needs you too.",
  "Don't make me stay behind.",
  "Remember Miles in your plans.",
  "I'm still part of the quest.",
  "Don't leave me in the cold.",
  "Miles is waiting patiently.",
  "Don't forget to include me.",
  "I'm right here with you.",
  "Don't leave your companion behind.",
  "Miles is ready to assist.",
  "Don't make me feel forgotten.",
  "I'm here to help, don't leave me.",
  "Don't leave Miles behind in the fog.",
  "I'm still part of the journey.",
  "Miles is counting on you.",
  "Don't leave me out of the fight.",
  "I'm still here, ready to go.",
  "Don't forget about your loyal friend Miles.",
  "Miles won't leave you stranded.",
  "I'm here, don't leave me out.",
  "Don't abandon Miles in the wilds.",
  "I'm still part of the team.",
  "Don't leave me in the shadows.",
  "Miles is still here for you.",
  "Don't make me wait again.",
  "I'm here, remember me.",
  "Don't leave your friend Miles behind.",
  "Don't let the DM know I'm watching him...",
];

export const MILES_SEE_CAMPAIGNS_PROMPTS: string[] = [
  "Would you like to see the campaigns?",
  "Interested in exploring the campaigns?",
  "How about a look at the campaigns?",
  "Shall we review the campaigns?",
  "Ready to view the campaigns?",
  "Would you like to browse through the campaigns?",
  "Curious about the campaigns on the table?",
  "Fancy a look at the campaigns?",
  "Should I show you the list of campaigns?",
  "How about checking out the campaigns?",
  "Would you care to see the campaigns on display?",
  "Can I interest you in a tour of the campaigns?",
  "How about a glance at the campaigns?",
  "Do you fancy exploring the campaigns?",
  "Might you want to check out the campaigns?",
  "Interested in seeing the campaigns?",
  "Would you like to get a list of campaigns?",
  "Curious to see which campaigns are uh... just click the button!",
  "Care to view the campaigns set up for adventure?",
  "Want to see the campaigns?",
  "Shall I pull up the list of campaigns for you?",
  "Would you like to examine the campaigns?",
  "Do you want to browse the list of campaigns?",
  "Interested in a rundown of campaigns?",
  "Should I display the campaigns right now?",
  "Ready for a tour of the latest campaigns?",
  "Can I pull up the campaigns for you?",
  "WHAT DO YOU WANT!?",
];

export const MILES_KNOCK_KNOCK_RESPONSES: string[] = [
  "Haha! That's a good one! Would have been even better if you said \"Orange you glad I DIDN'T LEAVE MILES BEHIND?\"",
  'Good one! Next time, I would have said "Don\'t forget about me, Miles!"',
  "LOL! You know, Miles would have loved that punchline. BUT YOU LEFT ME BEHIND!",
  "Nice! Don't leave Me out of the next joke.",
  "Haha! Miles here, still waiting to be part of the joke.",
  "Great! Just remember, Miles is always part of the fun. IF YOU DON'T LEAVE ME BEHIND!",
  "Haha! Don't leave your buddy Miles hanging like you did before.",
  "Good joke! Miles won't be forgotten this time.",
  "LOL! Miles is always here for the laughs. No.. Wait.. You left me behind!",
  "Nice one! Next time, include Me in the punchline.",
  "Great! Don't leave Miles behind in the laughs.",
  "Haha! Miles is part of the joke now.",
];

export const NO_DM_ROLE_MSG = "You do not have the DM role.";
